version: "3"

services:
    delete-indexes:
        image: playdingnow/delete-outdated-es-indexes:1.3
        container_name: delete-outdated
        environment:
            - eshost=elasticsearch
            - esport=9200
            - esmaxdays=1

    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
        container_name: elasticsearch
        environment:
            - xpack.security.enabled=false
            - bootstrap.memory_lock=true
            - ES_JAVA_OPTS=-Xms4g -Xmx8g
            - discovery.type=single-node
        ulimits:
            memlock:
                soft: -1
                hard: -1
        ports:
            - 9200:9200
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9200"]
            interval: 10s
            timeout: 5s
            retries: 3

    kibana:
        image: docker.elastic.co/kibana/kibana:7.5.1
        container_name: kibana
        ports:
            - 5601:5601
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:5601"]
            interval: 10s
            timeout: 5s
            retries: 3
        depends_on: ["elasticsearch"]

    apm-server:
        image: docker.elastic.co/apm/apm-server:7.5.1
        container_name: apm-server
        ports:
            - 8200:8200
        environment:
            - output.elasticsearch.hosts=['http://elasticsearch:9200']
            - apm-server.host="0.0.0.0:8200"
            - setup.kibana.host="kibana:5601"
            - setup.template.enabled=true
            - logging.to_files=false
            - apm-server.kibana.enabled=true
        depends_on: ["elasticsearch", "kibana"]
